name: The Gatekeeper

on: [push]

jobs:
    gatekeep:
        runs-on: ubuntu-latest
        steps:
          - name: Use actor
            run: echo "https://api.github-star-counter.workers.dev/user/${{ github.actor }}"