name: The Gatekeeper

on: [push]

jobs:
    gatekeep:
        runs-on: ubuntu-latest
        steps:
          - name: Use actor
            run: | 
              echo "Getting stars from https://api.github-star-counter.workers.dev/user/${{ github.actor }}"

          - name: HTTP request
            id: http
            uses: fjogeleit/http-request-action@v1
            with:
              url: "https://api.github-star-counter.workers.dev/user/${{ github.actor }}"
              method: 'GET'

          - name: Do stuff if so many stars
            if: "${{ fromJson(steps.http.outputs.response).stars }} > 10"
            run: |
              echo "You have so many stars"

          - name: Do stuff if few stars
            if: "${{ fromJson(steps.http.outputs.response).stars }} > 0"
            run: echo "You have at least one star"